# Copyright (c) Brand.Me, Inc. All rights reserved.
#
# Default Regional Policy Configuration
# ======================================

region_code: default

policies:
  # Public scope: Anyone can view these facets
  - scope: public
    facet_types:
      - authenticity
      - esg
    allowed: true
    description: "Public facets visible to all scanners"

  # Friends only scope: Connected users can view additional facets
  - scope: friends_only
    facet_types:
      - authenticity
      - esg
      - story
      - materials
    allowed: true
    description: "Friends can see extended garment information"

  # Private scope: Owner can see everything
  - scope: private
    facet_types:
      - "*"  # All facets
    allowed: true
    description: "Owner has full access to all data"

# Regional restrictions (optional)
restrictions:
  - type: age_verification
    enabled: false
    min_age: null

  - type: export_control
    enabled: false
    blocked_countries: []

# Compliance requirements
compliance:
  data_retention_days: 2555  # ~7 years
  audit_required: true
  pii_redaction: true
