#!/usr/bin/env node
// Generates CSS custom properties and TypeScript constants from
// docs/design/brandme/contracts/design-tokens.json (read-only spec input).
//   node scripts/generate.mjs [--check]
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const pkg = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = resolve(pkg, '../../docs/design/brandme/contracts/design-tokens.json');
const t = JSON.parse(readFileSync(SRC, 'utf8'));
const check = process.argv.includes('--check');
const kebab = (s) => s.replace(/_/g, '-');
const header = '/* GENERATED by packages/design-system/scripts/generate.mjs from design-tokens.json ' + t.schema_version + ' — do not edit. */\n';

const colorVars = (scheme) => Object.entries(t.color).map(([k, v]) => `  --bm-color-${kebab(k)}: ${v[scheme]};`).join('\n');
const ease = `cubic-bezier(${t.motion.easing.join(', ')})`;
const font = (f) => `"${f.family}", ${f.fallback}`;
const m = t.motion;

const css = `${header}
:root {
  color-scheme: light;
${colorVars('light')}
  --bm-font-display: ${font(t.font.display)};
  --bm-font-body: ${font(t.font.body)};
  --bm-font-evidence: ${t.font.evidence.family}, ${t.font.evidence.fallback};
  --bm-type-body: ${t.type.body_px}px;
  --bm-type-body-line: ${t.type.body_line_px}px;
  --bm-type-support: ${t.type.support_px}px;
  --bm-type-support-line: ${t.type.support_line_px}px;
  --bm-type-display: clamp(${t.type.display_mobile_px[0]}px, 6vw, ${t.type.display_mobile_px[1]}px);
  --bm-type-display-line: ${t.type.display_line_height};
  --bm-type-section: clamp(${t.type.section_px[0]}px, 3vw, ${t.type.section_px[1]}px);
  --bm-type-card: ${t.type.card_px}px;
  --bm-type-card-line: ${t.type.card_line_px}px;
${t.spacing_px.map((v, i) => `  --bm-space-${i + 1}: ${v}px;`).join('\n')}
${Object.entries(t.radius_px).map(([k, v]) => `  --bm-radius-${kebab(k)}: ${v}px;`).join('\n')}
  --bm-target-min: ${t.layout.target_min_px}px;
  --bm-action-height: ${t.layout.primary_action_height_px[0]}px;
  --bm-action-height-lg: ${t.layout.primary_action_height_px[1]}px;
  --bm-reading-max: ${t.layout.reading_max_ch}ch;
  --bm-content-max: ${t.layout.content_max_px}px;
  --bm-bottom-nav: ${t.layout.bottom_nav_px}px;
${Object.entries(t.z_index).map(([k, v]) => `  --bm-z-${kebab(k)}: ${v};`).join('\n')}
  --bm-ease: ${ease};
  --bm-motion-button: ${m.button_ms}ms;
  --bm-motion-sheet: ${m.sheet_ms}ms;
  --bm-motion-route: ${m.route_ms[1]}ms;
  --bm-motion-slider: ${m.slider_ms}ms;
  --bm-motion-selection: ${m.selection_ms}ms;
  --bm-motion-room: ${m.room_ms}ms;
  --bm-motion-badge: ${m.badge_max_ms}ms;
  --bm-motion-points: ${m.points_max_ms}ms;
  --bm-motion-rollback: ${m.rollback_ms}ms;
  --bm-motion-response: ${m.response_ms}ms;
}

@media (min-width: ${t.layout.breakpoints_px[2]}px) {
  :root { --bm-type-display: clamp(${t.type.display_desktop_px[0]}px, 5vw, ${t.type.display_desktop_px[1]}px); }
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    color-scheme: dark;
${colorVars('dark').replace(/^/gm, '  ')}
  }
}
:root[data-theme="dark"] {
  color-scheme: dark;
${colorVars('dark')}
}

/* Reduced motion (${m.reduced_motion}): one source for DOM and scene code.
   Sheets become 120 ms fades; route/slider/selection/points become immediate. */
@media (prefers-reduced-motion: reduce) {
  :root:not([data-motion="full"]) {
    --bm-motion-sheet: 120ms;
    --bm-motion-route: 0ms;
    --bm-motion-slider: 0ms;
    --bm-motion-selection: 0ms;
    --bm-motion-room: 0ms;
    --bm-motion-badge: 0ms;
    --bm-motion-points: 0ms;
    --bm-motion-rollback: 0ms;
    --bm-motion-response: 0ms;
  }
}
:root[data-motion="reduced"] {
  --bm-motion-sheet: 120ms;
  --bm-motion-route: 0ms;
  --bm-motion-slider: 0ms;
  --bm-motion-selection: 0ms;
  --bm-motion-room: 0ms;
  --bm-motion-badge: 0ms;
  --bm-motion-points: 0ms;
  --bm-motion-rollback: 0ms;
  --bm-motion-response: 0ms;
}
`;

const ts = `// GENERATED by packages/design-system/scripts/generate.mjs from design-tokens.json ${t.schema_version} — do not edit.
export const tokens = ${JSON.stringify(t, null, 2)} as const;

export type ColorToken = keyof typeof tokens.color;
export type ColorScheme = 'light' | 'dark';
export const cssVar = (name: ColorToken): string => \`var(--bm-color-\${name.replace(/_/g, '-')})\`;
export const easing = tokens.motion.easing;
export const closetAddSegmentsMs = tokens.motion.closet_add_segments_ms;
export const sceneCamera = tokens.scene.camera;
export const qualityTiers = tokens.scene.quality;
`;

const outputs = new Map([
  ['generated/tokens.css', css],
  ['generated/tokens.ts', ts],
]);
let drift = 0;
for (const [rel, content] of outputs) {
  const file = join(pkg, rel);
  const cur = existsSync(file) ? readFileSync(file, 'utf8') : null;
  if (check) { if (cur !== content) { drift++; console.error(`drift: ${rel}`); } }
  else if (cur !== content) { mkdirSync(dirname(file), { recursive: true }); writeFileSync(file, content); console.log(`wrote ${rel}`); }
}
if (check) { if (drift) process.exit(1); console.log('design-system: no drift'); }
