{{- if .Values.cube.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "brandme.fullname" . }}-cube
  labels:
    app: cube
    tier: backend
    {{- include "brandme.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.cube.replicaCount }}
  selector:
    matchLabels:
      app: cube
  template:
    metadata:
      labels:
        app: cube
        tier: backend
    spec:
      containers:
      - name: cube
        image: {{ .Values.cube.image.repository }}:{{ .Values.cube.image.tag }}
        ports:
        - containerPort: 8007
          name: http
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: brandme-secrets
              key: database-url
        - name: POLICY_URL
          value: "http://{{ include "brandme.fullname" . }}-policy:8001"
        - name: ORCHESTRATOR_URL
          value: "http://{{ include "brandme.fullname" . }}-orchestrator:8002"
        - name: COMPLIANCE_URL
          value: "http://{{ include "brandme.fullname" . }}-compliance:8004"
        - name: IDENTITY_URL
          value: "http://{{ include "brandme.fullname" . }}-identity:8005"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8007
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8007
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          {{- toYaml .Values.cube.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "brandme.fullname" . }}-cube
  labels:
    app: cube
spec:
  type: {{ .Values.cube.service.type }}
  ports:
  - port: {{ .Values.cube.service.port }}
    targetPort: 8007
    protocol: TCP
    name: http
  selector:
    app: cube
{{- end }}
