# GENERATED by packages/contracts/scripts/generate.mjs — do not edit.
# generated by datamodel-codegen:
#   filename:  schema.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class BrandmeDomain(RootModel[Any]):
    root: Any = Field(
        ...,
        description='Implementation requirements, not a claim that corresponding endpoints already exist. Select a definition through $ref.',
        title='BrandmeDomain',
    )


class Identifier(RootModel[UUID]):
    root: UUID


class Environment(Enum):
    demo = 'demo'
    development = 'development'
    sandbox = 'sandbox'
    production = 'production'


class Money(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    amount_minor: str = Field(..., pattern='^(0|[1-9][0-9]{0,17})$')
    currency: str = Field(..., pattern='^[A-Z]{3}$')


class AxisKey(Enum):
    temperature = 'temperature'
    sport_couture = 'sport_couture'
    expression = 'expression'
    fit_language = 'fit_language'
    detail = 'detail'
    novelty = 'novelty'
    color = 'color'
    finish = 'finish'
    structure = 'structure'
    setting = 'setting'
    exploration = 'exploration'
    utility = 'utility'


class AxisValues(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    temperature: float | None = Field(..., ge=0.0, le=100.0)
    sport_couture: float | None = Field(..., ge=0.0, le=100.0)
    expression: float | None = Field(..., ge=0.0, le=100.0)
    fit_language: float | None = Field(..., ge=0.0, le=100.0)
    detail: float | None = Field(..., ge=0.0, le=100.0)
    novelty: float | None = Field(..., ge=0.0, le=100.0)
    color: float | None = Field(..., ge=0.0, le=100.0)
    finish: float | None = Field(..., ge=0.0, le=100.0)
    structure: float | None = Field(..., ge=0.0, le=100.0)
    setting: float | None = Field(..., ge=0.0, le=100.0)
    exploration: float | None = Field(..., ge=0.0, le=100.0)
    utility: float | None = Field(..., ge=0.0, le=100.0)


class PersonaChange(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    axis: AxisKey
    value: float | None = Field(..., ge=0.0, le=100.0)
    locked: bool


class PersonaPatch(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    changes: list[PersonaChange] = Field(..., max_length=12)
    learning_enabled: bool | None = None
    client_revision: str = Field(..., max_length=64, min_length=1)


class PersonaProfile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    member_id: UUID
    version: str = Field(..., pattern='^(0|[1-9][0-9]{0,17})$')
    declared_axes: AxisValues
    inferred_axes: AxisValues
    effective_axes: AxisValues
    locked_axes: list[AxisKey] = Field(..., max_length=12)
    learning_enabled: bool
    updated_at: AwareDatetime


class RoomTemplateId(Enum):
    walnut_atelier = 'walnut_atelier'
    limestone_gallery = 'limestone_gallery'
    garden_studio = 'garden_studio'


class SemanticGroup(Enum):
    rail_left = 'rail.left'
    rail_right = 'rail.right'
    shelf_shoes = 'shelf.shoes'
    shelf_folded = 'shelf.folded'
    tray_accessories = 'tray.accessories'
    stand_outfit = 'stand.outfit'


class ClosetPlacement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    wardrobe_item_id: UUID
    layout_id: UUID
    room_template_id: RoomTemplateId
    semantic_group: SemanticGroup
    slot_id: str = Field(..., max_length=64, min_length=1)
    position_meters: list[float] = Field(..., max_length=3, min_length=3)
    rotation_quaternion: list[float] = Field(..., max_length=4, min_length=4)
    uniform_scale: float = Field(..., gt=0.0, le=10.0)
    asset_revision: str = Field(..., max_length=128, min_length=1)
    version: str = Field(..., pattern='^(0|[1-9][0-9]{0,17})$')


class Fidelity(Enum):
    p0 = 'P0'
    p1 = 'P1'
    p2 = 'P2'
    p3 = 'P3'
    p4 = 'P4'


class SourceType(Enum):
    member_upload = 'member_upload'
    licensed_provider = 'licensed_provider'
    original_demo = 'original_demo'
    issuer = 'issuer'
    manufacturer = 'manufacturer'


class MediaEvidence(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    asset_id: UUID
    fidelity: Fidelity
    source_type: SourceType
    rights_policy_ref: str = Field(..., max_length=256, min_length=1)
    label: str = Field(..., max_length=256, min_length=1)
    dimensions_calibrated: bool
    environment: Environment


class Collection(Enum):
    owned = 'owned'
    want = 'want'
    on_the_way = 'on_the_way'
    digital = 'digital'
    archive = 'archive'


class ClaimLevel(Enum):
    self_reported = 'self_reported'
    receipt_backed = 'receipt_backed'
    tag_verified = 'tag_verified'
    issuer_attested = 'issuer_attested'


class WardrobeItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    member_id: UUID
    title: str = Field(..., max_length=200, min_length=1)
    collection: Collection
    product_id: UUID | None = None
    asset_instance_id: UUID | None = None
    claim_level: ClaimLevel
    version: str = Field(..., pattern='^(0|[1-9][0-9]{0,17})$')


class SubjectType(Enum):
    wardrobe_item = 'wardrobe_item'
    catalog_product = 'catalog_product'
    outfit_version = 'outfit_version'


class DiscussionMode(Enum):
    blind_until_response = 'blind_until_response'
    open = 'open'


class DecisionCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    subject_type: SubjectType
    subject_id: UUID
    prompt: str = Field(..., max_length=280, min_length=1)
    recipient_ids: list[UUID] = Field(..., max_length=12, min_length=1)
    duration_seconds: Literal[300]
    discussion_mode: DiscussionMode


class Choice(Enum):
    yes = 'yes'
    pass_ = 'pass'
    alternative = 'alternative'


class DecisionResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    choice: Choice
    alternative_ref: UUID | None = None
    note: str | None = Field(None, max_length=500)


class SubjectType1(Enum):
    outfit_version = 'outfit_version'
    wardrobe_item = 'wardrobe_item'
    closet_capsule = 'closet_capsule'
    persona_snapshot = 'persona_snapshot'
    badge = 'badge'


class Audience(Enum):
    selected_members = 'selected_members'
    unlisted = 'unlisted'
    public = 'public'


class AllowedField(RootModel[str]):
    root: str = Field(..., max_length=64, min_length=1)


class ShareCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    subject_type: SubjectType1
    subject_id: UUID
    audience: Audience
    allowed_fields: list[AllowedField] = Field(..., max_length=30, min_length=1)
    recipient_ids: list[UUID] = Field(..., max_length=100)
    expires_at: AwareDatetime


class Name(Enum):
    catalog_search = 'catalog.search'
    catalog_detail = 'catalog.detail'
    catalog_feed = 'catalog.feed'
    catalog_images = 'catalog.images'
    catalog_3d = 'catalog.3d'
    inventory_read = 'inventory.read'
    price_quote = 'price.quote'
    cart_create = 'cart.create'
    cart_update = 'cart.update'
    checkout_handoff = 'checkout.handoff'
    checkout_submit = 'checkout.submit'
    orders_read = 'orders.read'
    orders_webhook = 'orders.webhook'
    returns_request = 'returns.request'
    refunds_read = 'refunds.read'
    affiliate_attribution = 'affiliate.attribution'
    receipts_import = 'receipts.import'
    tryon_photo = 'tryon.photo'
    tryon_live = 'tryon.live'
    rights_issue = 'rights.issue'
    rights_transfer = 'rights.transfer'
    rights_reprint = 'rights.reprint'
    manufacture_quote = 'manufacture.quote'
    manufacture_submit = 'manufacture.submit'


class State(Enum):
    unconfigured = 'unconfigured'
    sandbox = 'sandbox'
    verified = 'verified'
    degraded = 'degraded'
    suspended = 'suspended'
    unsupported = 'unsupported'


class EvidenceRef(RootModel[str]):
    root: str = Field(..., max_length=256, min_length=1)


class Capability(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Name
    state: State
    reason_code: str = Field(..., max_length=80, min_length=1)
    last_checked_at: AwareDatetime | None = None
    evidence_ref: EvidenceRef | None = None


class CountryCode(RootModel[str]):
    root: str = Field(..., pattern='^[A-Z]{2}$')


class ProviderPublic(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    provider_id: str = Field(..., max_length=80, min_length=1)
    display_name: str = Field(..., max_length=120, min_length=1)
    environment: Environment
    capabilities: list[Capability] = Field(..., max_length=50)
    country_codes: list[CountryCode] = Field(..., max_length=250)
    disclosure: str = Field(..., max_length=1200)


class QuoteLine(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    variant_id: UUID
    source_variant_ref: str = Field(..., max_length=256, min_length=1)
    quantity: int = Field(..., ge=1, le=99)
    unit_price: Money
    line_total: Money


class CheckoutQuote(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    environment: Environment
    provider_id: str = Field(..., max_length=80, min_length=1)
    merchant_id: str = Field(..., max_length=256, min_length=1)
    payee_ref: str = Field(..., max_length=256, min_length=1)
    cart_id: UUID
    cart_revision: str = Field(..., pattern='^(0|[1-9][0-9]{0,17})$')
    lines: list[QuoteLine] = Field(..., max_length=100, min_length=1)
    subtotal: Money
    tax: Money
    shipping: Money
    discount: Money
    total: Money
    delivery_ref: str = Field(..., max_length=256, min_length=1)
    terms_hash: str = Field(..., max_length=128, min_length=1)
    quote_hash: str = Field(..., max_length=128, min_length=1)
    issued_at: AwareDatetime
    expires_at: AwareDatetime


class PurchaseRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    quote_id: UUID
    approval_id: UUID
    delegation_id: UUID | None = None


class Network(Enum):
    local = 'local'
    preview = 'preview'
    preprod = 'preprod'
    mainnet = 'mainnet'


class Operation(Enum):
    issue = 'issue'
    prove_control = 'prove_control'
    transfer = 'transfer'
    consume_reprint = 'consume_reprint'
    attest_manufacture = 'attest_manufacture'
    revoke = 'revoke'
    recover = 'recover'


class State1(Enum):
    prepared = 'prepared'
    awaiting_wallet = 'awaiting_wallet'
    proving = 'proving'
    submitted = 'submitted'
    observed = 'observed'
    reconciling = 'reconciling'
    finalized = 'finalized'
    failed = 'failed'
    cancelled = 'cancelled'


class TransactionId(RootModel[str]):
    root: str = Field(..., max_length=256, min_length=1)


class ObservedBlock(RootModel[str]):
    root: str = Field(..., pattern='^(0|[1-9][0-9]{0,17})$')


class ChainOperation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    network: Network
    contract_ref: str = Field(..., max_length=256, min_length=1)
    operation: Operation
    state: State1
    request_digest: str = Field(..., max_length=128, min_length=1)
    transaction_id: TransactionId | None = None
    observed_block: ObservedBlock | None = None
    updated_at: AwareDatetime


class AllowedManufacturerId(RootModel[str]):
    root: str = Field(..., max_length=256, min_length=1)


class LicensePermissions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    display: bool
    transfer: bool
    repair_parts: bool
    personal_reprint: bool
    commercial_reprint: bool
    remaining_quota: int = Field(..., ge=0, le=1000000)
    allowed_manufacturer_ids: list[AllowedManufacturerId] = Field(..., max_length=100)
    policy_digest: str = Field(..., max_length=128, min_length=1)
    expires_at: AwareDatetime


class PrivacyClass(Enum):
    public = 'public'
    member_private = 'member_private'
    restricted = 'restricted'


class EventEnvelope(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    event_id: UUID
    event_type: str = Field(..., pattern='^[a-z]+(\\.[a-z_]+)+$')
    schema_version: str = Field(..., max_length=32, min_length=1)
    aggregate_type: str = Field(..., max_length=80, min_length=1)
    aggregate_id: UUID
    aggregate_version: str = Field(..., pattern='^(0|[1-9][0-9]{0,17})$')
    occurred_at: AwareDatetime
    environment: Environment
    actor_ref: str = Field(..., max_length=256, min_length=1)
    correlation_id: UUID
    causation_id: UUID | None = None
    privacy_class: PrivacyClass
    payload: dict[str, Any] = Field(
        ...,
        description='Must be validated by the registered event-type-specific schema; arbitrary payloads are not accepted at runtime.',
    )


class Problem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: AnyUrl
    title: str = Field(..., max_length=200, min_length=1)
    status: int = Field(..., ge=400, le=599)
    code: str = Field(..., max_length=80, min_length=1)
    detail: str = Field(..., max_length=1000, min_length=1)
    instance: str = Field(..., max_length=256, min_length=1)
    request_id: UUID
    retryable: bool
